# Generated by Django 5.0.7 on 2025-04-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='modelo',
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='fs.marca')),
            ],
        ),
    ]
