# Generated by Django 5.0.7 on 2025-04-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_remove_marca_modelo_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='modeloandmarca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fs.modelo'),
        ),
    ]
