# Generated by Django 5.0.7 on 2025-04-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fs', '0004_remove_producto_marca_producto_modeloandmarca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cedula',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='modeloandmarca',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='preciounitario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Jurídico')], default='natural', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ClienteJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fs.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('ganancia', models.FloatField()),
                ('iva', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.proveedor')),
            ],
        ),
    ]
