# Generated by Django 5.0.7 on 2025-05-10 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteNatural',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='natural', serialize=False, to='fs.cliente')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='fs.producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='cantidadporproducto',
            new_name='cantidad_por_producto',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='metododepago',
            new_name='metodo_de_pago',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='idempleado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='clientejuridico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detalleproveedor',
            name='metododepago',
        ),
        migrations.RemoveField(
            model_name='detalleproveedor',
            name='numerocomprobante',
        ),
        migrations.RemoveField(
            model_name='detalleproveedor',
            name='tipocomprobante',
        ),
        migrations.RemoveField(
            model_name='detalleproveedor',
            name='totalapagar',
        ),
        migrations.RemoveField(
            model_name='precioproveedorproducto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='precioproveedorproducto',
            name='ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fechadeactualizacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precioinstalacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='totalapagar',
        ),
        migrations.AddField(
            model_name='bodega',
            name='empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='fs.empleado'),
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='ruc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleproveedor',
            name='metodo_de_pago',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleproveedor',
            name='numero_comprobante',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='detalleproveedor',
            name='tipo_comprobante',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='detalleproveedor',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_instalacion',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'JurÃ\xaddico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='juridico', serialize=False, to='fs.cliente'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='razon_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detalleproveedor',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleproveedor',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detalleproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fs.producto'),
        ),
        migrations.AlterField(
            model_name='detalleproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fs.proveedor'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fs.venta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='precioproveedorproducto',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='precioproveedorproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precioproveedorproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_proveedor', to='fs.producto'),
        ),
        migrations.AlterField(
            model_name='precioproveedorproducto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_producto', to='fs.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigobodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='fs.bodega'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='fs.modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='fs.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='fs.empleado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='instalacion',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
    ]
