# Generated by Django 5.0.7 on 2025-05-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_clientenatural_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='fs.precioproveedorproducto'),
        ),
    ]
